### ISSUE TITLE
Basic Acceptance Criteria Checklist

### ISSUE THREAD

**Issue by EmilyNecciai** [EmilyNecciai/urban-octo-telegram#1]
- [x] 1. Application's links all function correctly.
- [x] 2. Application's CSS selectors and properties are consolidated and organized to follow semantic structure.
- [x] 3. Application's CSS file is properly commented.
- [x] 4. Application deployed at live URL.
- [x] 5. Application loads with no errors.
- [x] 6. Application GitHub URL submitted.
- [x] 7. GitHub repository that contains application code.
- [x] 8. Application resembles (at least 90%) screenshots provided in challenge instructions.
- [x] 9. Repository has a unique name.
- [x] 10. Repository follows best practices for file structure and naming conventions.
- [x] 11. Repository follows best practices for class/id naming conventions, indentation, quality comments, etc.
- [x] 12. Repository contains multiple descriptive commit messages.
- [x] 13. Repository contains quality README file with description, screenshot, and link to deployed application.
